# MongoDB params
#===================================
mongodb:
  host: "localhost" # mongodb server address
  port: 27017 # mongodb server port
  db: "family-screening" # database name
  username: # for auth
  password: # for auth


# docker
docker:
  mongodb:
    host: "db" # mongodb server address
    port: 27017 # mongodb server port
    db: "sibyl" # database name
    username: # for auth
    password: # for auth

# FLASK
#===================================
flask:
  PORT: 3000
  ENV: "production" # development, production, test
  DEBUG: False
  TESTING: False
  BUNDLE_ERRORS: True

# LOGGING
#===================================
log_filename: "screening_log.csv"

# PRE-SAVED INFORMATION
#===================================
# Location of pre-computed feature distribution information
# Useful in cases where the dataset cannot be shared
# null if this information should be calculated at runtime
feature_distribution_location: "sibyl/db/precomputed/agg_distributions.json"
