use_rows: false
output_type: numeric
output_format_string: ${:,.2f}
output_sentiment_is_negative: false
terms:
  entity: House
  feature: Factor
  prediction: Price
  increasing: Beneficial
  decreasing: Harmful
