use_rows: true
row_label:
output_type: boolean
show_probs: false
output_pos_label: good
output_neg_label: bad
output_sentiment_is_negative: true
terms:
  entity: House
  feature: Factor
  prediction: Price
  increasing:
  decreasing:
