version: '3'
services:
  db:
    image: mongo:4.0
    container_name: sibyl_db
    ports:
      - '127.0.0.1:27018:27017'
    command: bash -c "mongod --bind_ip_all --port 27017 --logpath /sibyl/log/db.log --fork && tail -F anything"
    volumes:
      - ./db/data:/sibyl/data
      - ./db/log:/sibyl/log
      - ./db/dump:/sibyl/dump
  app:
    build: .
    container_name: sibyl
    depends_on:
      - db
    ports:
      - '3000:3000'
    command: sibyl run --env production -v --docker
