# Configurations for database preprocessing
# =================================================================================================

# Name of database to create
database_name: "family-screening"
# Name of directory in dbdata with csv files (if different from database_name)
directory:
# If true, automatically drop existing database
DROP_OLD: True

# Training data configurations
# =================================================================================================
# If true, include the full training database in loading (set to False if privacy is a concern)
include_database: True
# Number of entries from database to include
num_from_database: 1000


# Entity processing configurations
# =================================================================================================
# filepath to fitted, pickled Pyreal transformers
pre_transformers_fn:
# filepath to mappings csv for one-hot decoder (TODO: add sample format)
one_hot_decode_fn: "mappings.csv"

# Model processing configurations
# =================================================================================================
target: "PRO_PLSM_NEXT730_DUMMY"
pickle_model_fn:
weights_fn: "weights.csv"
threshold_fn: "thresholds.csv"
one_hot_encode_fn: "mappings.csv"
model_transformers_fn:
importance_fn: "importances.csv"
explainer_fn:
