 # Configurations for database preprocessing
# =================================================================================================

# Name of database to create
database_name: "housing"
# Name of directory in dbdata with csv and pkl files (if different from database_name)
directory: "housing"
# If true, automatically drop existing database
DROP_OLD: True

# Training data configurations
# =================================================================================================
# Name of database file
dataset_fn: "entities.csv"

# Entity processing configurations
# =================================================================================================
# If true, impute data using pyreal.MultiTypeImputer()
impute: True

# Model processing configurations
# =================================================================================================
# Name of target column in database
target: "SalePrice"
# filename of pickled model
pickle_model_fn: "model.pkl"
# filename of pickled explainer
explainer_fn: "explainer.pkl"
# shap type to use for explainer if not provided
shap_type: "linear" # TODO: make this process smoother

# GUI configurations
# =================================================================================================
# Preset term for gui config, used to automatically fill in some configurations. Overridden by other configs
gui_preset: "profit_usd"
