name: PyPI Deploy

on:
  push:
    tags:
    - '*'

jobs:

  # Automatically deploy releases to PyPI for each tagged commit. This
  # uses the API Token feature (https://pypi.org/help/#apitoken). After
  # obtaining an API token from PyPI, add it to your github secrets with
  # the name `pypi_password`.
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Build distribution
        run: make dist
    
      - name: Publish package
        if: startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
