name: Test Python

on:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10"]
        mongodb-version: ['6.0', '7.0']

    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Start MongoDB
        uses: ankane/setup-mongodb@v1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true' # Only run if the cache is old
        run: poetry install --no-interaction

      - name: Populate DB
        run: poetry run invoke prepare-sample-db

      - name: Lint
        run: poetry run invoke lint

      - name: Test Unit
        run: poetry run invoke test-unit

      - name: Test Scripts
        run: poetry run invoke test-scripts
